[project]
name = "sense_EEG"
dynamic = ["version"]
dependencies = []

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict = true
show_column_numbers = true
pretty = true
files = ["workspace/src"]