/eeg_publisher1/mock_publisher:
  ros__parameters:
    # these are as written in the gtec header file
    sample_rate: 256 		     		# unsigned short int 0 to 65535 per second? (4800 Hz) 
    number_of_scans:          		# int not sure what this is
    enable_trigger_line: 1			# gt_bool = unsigned int ( set 1 = true based on eegdev) a separate (phyical trigger button) Probably not required as we can set up a separate ros node.
    slave_mode: 0               		# gt_bool = unsigned int ( set 0 = false based on eegdev) probably useful if you want to stack multiple units (more than 16 channels) Not necessary
    enable_sc: 0                		# gt_bool = unsigned int ( set 0 = false based on eegdev) don't know. Probably not needed (there is an sc port on the device)
    common_ground: [ 0, 0, 0, 0 ] 	        # an array of gt_bool from gAPI.h GT_USBAMP_NUM_GROUND = 4 # required
    common_reference: [ 0, 0, 0, 0 ]            # an array of gt_bool from gAPI.h GT_USBAMP_NUM_REFERENCE = 4 # required
    mode: 0                                     # gt_usbamp_device_mode . enum (GT_MODE_NORMAL, GT_MODE_IMPEDANCE, GT_MODE_CALIBRATE, GT_MODE_COUNTER) NORMAL is required. Impedance is useful to make sure that electrodes remain attached )you wouldn't record it as a signal- unclear how you'd publish that from a ros node.) CALIBRATE and COUNTER unkown.
    scan_dio: 1					# gt_bool. eegdev sets to true (digital input / output) There are 2 of these on the devicve
    version: 0.0				# float - don't know. Not set in eegdev
    bandpass: [ int x 16  ]                     # array of ints. from gAPI.h GT_USBAMP_NUM_ANALOG_IN is 16 # not required yet
    notch: [ int x 16 ]                         # array of ints. from gAPI.h GT_USBAMP_NUM_ANALOG_IN is 16 # not required yet
    bipolar: [ -2, -2, -2, -2, -2, ... ]        # array of ints. from gAPI.h GT_USBAMP_NUM_ANALOG_IN is eegdev sets to GT_BIPOLAR_DERIVATION_NONE = -2 (Defines what other channel you are bipolar with) Presumably the number in the array defines which channel you are linked with - required. If you link 2 channels you will only get one channel out.
    analog_in_channel: [ in x 16 ]              # array of uchar. from gAPI.h GT_USBAMP_NUM_ANALOG_IN is 16 unknown
    num_analog_in: 16                           # gt_size = unsigned long int unkown
    ao_config: a pointer 			# pointer to a gt_usbamp_analog_out_config object (see below)
    
	 
    # these are from mock publisher    
    num_channels: 8
    num_samples: 32
    sampling_rate: 256.0

# typedef struct usbamp_analog_out_config
#{
#  gt_usbamp_analog_out_shape shape;
#  short int offset;
#  short int frequency;
#  short int amplitude;
#} gt_usbamp_analog_out_config;
